core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    # index view
    url(r'^$', views.index, name='index') # for simple index-view
]

provenance/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core import views as coreviews
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', coreviews.IndexView.as_view(), name='index'),
    url(r'^prov_vo/', include('prov_vo.urls')),
    url(r'^vosi/', include('vosi.urls')),
    url(r'^raveprov/', include('raveprov.urls')),
    url(r'^admin/', admin.site.urls),
]

raveprov/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'raveprov'
urlpatterns = [
    # form for observation id, basic or details:
    url(r'^form/$', views.get_observationId, name='get_observationId'),
    url(r'^(?P<observation_id>[0-9a-zA-Z.:_-]+)/(?P<detail_flag>[a-z]+)/$', views.observationid_detail, name='observationid_detail'),
    url(r'^(?P<observation_id>[0-9a-zA-Z.:_-]+)/(?P<detail_flag>[a-z]+)/graphjson$', views.observationid_detailjson, name='observationid_detailjson'),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic

class IndexView(generic.TemplateView):
    template_name = 'core/index.html'

core/templates/core/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
<meta charset="utf-8"/>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/bootstrap.css' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}" >


<title>{% block title %}{% endblock %}</title>

<script type="text/javascript">
{% block javascript %}{% endblock %}
</script>

</head>
<body>

<div class="container-fluid">
{% block content %}{% endblock %}
</div>

<div style="clear:both"></div>
<p class="footer">RAVE provenance webapp</p>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}RAVE Provenance{% endblock %}

{% block content %}
<h1>RAVE Provenance</h1>
<h3>Provenance webapp prototype for the RAVE project</h3>
<p>
    Details about the RAVE project are available here:
    <a href="https://www.rave-survey.org/project/" target="_blank">RAVE webpage</a>.
</p>
<p>
    This is a prototype webapp for displaying provenance information of RAVE data, using the <a href="https://www.djangoproject.com/">Django framework</a> and the provenance package django-prov_vo.
</p>

<h4>General provenance endpoint</h4>
<p>
    Provenance specific links etc. can be found via the following link:
    <ul>
        <li>prov_vo endpoint: <a href="{% url 'prov_vo:index' %}">prov_vo</a></li>
    </ul>
</p>

<h4>RAVE specific provenance links</h4>
<ul>
    <li>Detail/basic provenance, with graph output: <a href="{% url 'raveprov:get_observationId' %}">Form for RAVE_OBS_IDs</a> (experimental)</li>
</ul>


<h4>Sources</h4>
<div>
    The sources for this web application are available at <a href="https://github.com/kristinriebe/provenance-rave/">GitHub: kristinriebe/provenance-rave</a>.<br>
    The sources for the prov_vo package are available at <a href="https://github.com/kristinriebe/provenance-rave/">GitHub: kristinriebe/django-prov_vo</a>.
</div>
{% endblock %}